apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: payment-sa # IMPORTANTE: Service Account para autenticação com AWS
      containers:
        - name: payment
          image: 239409137076.dkr.ecr.us-east-1.amazonaws.com/payment:TAG
          #image: hmouraf/fastfood:tech_fase2
          #image: hmouraf/soat-tech-challenge-fast-food-app:feature-build
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "800Mi" # Mínimo de memória garantida
              cpu: "250m"      # Mínimo de CPU garantida (0.25 cores)
            limits:
              memory: "1G" # Máximo de memória que o container pode usar
              cpu: "512m"      # Máximo de CPU que o container pode usar (0.5 cores)
          envFrom:
            - configMapRef:
                name: payment-configmap
          env:
            - name: NEW_RELIC_LICENSE_KEY
              value: "3b37ab2f3df2e57df99ba57f8e851b7dFFFFNRAL"
            - name: NEW_RELIC_APP_NAME
              value: "payment-app-service"
            - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
              value: "true"
            - name: NEW_RELIC_LOGS_IN_CONTEXT_ENABLED
              value: "true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-secrets # <- Nome do segredo que o External Secrets irá criar
                  key: DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secrets # <- Nome do segredo que o External Secrets irá criar
                  key: DATASOURCE_PASSWORD
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 60

          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 60
---

